apiVersion: privatecloud.mendix.com/v1alpha1
kind: MendixApp
metadata:
  name: my-app
  namespace: mattia
spec:
  database: # Specification of Database CR
    servicePlan: db1 #dev
  storage: # Specification of Storage CR
    servicePlan: stg1 #dev
  mendixRuntimeVersion: 10.18.0 # Studio Pro version of the Mendix app
  sourceURL: ${PUBLIC_URL} # https://example.com/example-app.mda # URL of App's source MDA or prebuilt OCI image
  appURL: myapp.mendix.envnt.tech # URL to access the app
  replicas: 1 # Number of replicas, set to 0 to stop all replicas

  
  runtime: # Configuration of the Mendix Runtime
    logAutosubscribeLevel: INFO # Default logging level
    mxAdminPassword: V2VsYzBtZSE= # base64 encoded password for MendixAdmin user. In this example, 'Welc0me!'; can be left empty keep password unchanged
    debuggerPassword: V2VsYzBtZSE= # base64 encoded password for debuggerPassword. In this example, 'Welc0me!';
    dtapMode: D # Security & runtime mode: P for production, D for development
  
    
    # Mendix Runtime Jetty options, in JSON format; validated and applied by the mx-m2ee-sidecar container
    jettyOptions: |-
      {
        "max_form_content_size": 10485760,
        "use_blocking_connector": false
      }      
    customConfiguration: |-
      {
        "ApplicationRootUrl": "http://myapp.mendix.envnt.tech/"
      }      
